-- DropForeignKey
ALTER TABLE "TBL_CLIENTES" DROP CONSTRAINT "TBL_CLIENTES_id_municipio_fkey";

-- AddForeignKey
ALTER TABLE "TBL_CLIENTES" ADD CONSTRAINT "TBL_CLIENTES_id_municipio_fkey" FOREIGN KEY ("id_municipio") REFERENCES "TBL_MUNICIPIO"("id") ON DELETE NO ACTION ON UPDATE CASCADE;
