-- CreateTable
CREATE TABLE "TBL_EJERCICIO_RUTINA" (
    "id" TEXT NOT NULL,
    "nombre" TEXT NOT NULL,
    "descripcion" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "TBL_EJERCICIO_RUTINA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBL_RUTINA_ENTRENAMIENTO" (
    "id" TEXT NOT NULL,
    "nombre" TEXT NOT NULL,
    "descripcion" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "TBL_RUTINA_ENTRENAMIENTO_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TBL_REL_RUTINA_EJERCICIO" (
    "id" TEXT NOT NULL,
    "id_rutina_entrenamiento" TEXT NOT NULL,
    "id_ejercicio_rutina" TEXT NOT NULL,

    CONSTRAINT "TBL_REL_RUTINA_EJERCICIO_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "TBL_REL_RUTINA_EJERCICIO" ADD CONSTRAINT "TBL_REL_RUTINA_EJERCICIO_id_ejercicio_rutina_fkey" FOREIGN KEY ("id_ejercicio_rutina") REFERENCES "TBL_EJERCICIO_RUTINA"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBL_REL_RUTINA_EJERCICIO" ADD CONSTRAINT "TBL_REL_RUTINA_EJERCICIO_id_rutina_entrenamiento_fkey" FOREIGN KEY ("id_rutina_entrenamiento") REFERENCES "TBL_RUTINA_ENTRENAMIENTO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
