-- DropForeignKey
ALTER TABLE "TBL_CLIENTES" DROP CONSTRAINT "TBL_CLIENTES_id_contrato_fkey";

-- DropForeignKey
ALTER TABLE "TBL_INFORMACIONCHEQUEO" DROP CONSTRAINT "TBL_INFORMACIONCHEQUEO_id_cliente_fkey";

-- DropForeignKey
ALTER TABLE "TBL_PROGRESO" DROP CONSTRAINT "TBL_PROGRESO_id_chequeo_fkey";

-- DropForeignKey
ALTER TABLE "TBL_RUTINAS" DROP CONSTRAINT "TBL_RUTINAS_id_cliente_fkey";

-- AddForeignKey
ALTER TABLE "TBL_CLIENTES" ADD CONSTRAINT "TBL_CLIENTES_id_contrato_fkey" FOREIGN KEY ("id_contrato") REFERENCES "TBL_CONTRATOS"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBL_INFORMACIONCHEQUEO" ADD CONSTRAINT "TBL_INFORMACIONCHEQUEO_id_cliente_fkey" FOREIGN KEY ("id_cliente") REFERENCES "TBL_CLIENTES"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBL_PROGRESO" ADD CONSTRAINT "TBL_PROGRESO_id_chequeo_fkey" FOREIGN KEY ("id_chequeo") REFERENCES "TBL_INFORMACIONCHEQUEO"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TBL_RUTINAS" ADD CONSTRAINT "TBL_RUTINAS_id_cliente_fkey" FOREIGN KEY ("id_cliente") REFERENCES "TBL_CLIENTES"("id") ON DELETE CASCADE ON UPDATE CASCADE;
